export const en = {
  header: {
    more: 'More ▾',
    whoWeAre: 'Who We Are',
    whatWeDo: 'What We Do',
    practiceAreas: 'Practice Areas',
    partners: 'Partners',
    contact: 'Contact',
    insights: 'Publications',
    clientLogin: 'Client Login',
    backToPracticeAreas: 'Practice Areas',
    backToPartners: 'Our Partners',
    languageDeutsch: 'Deutsch',
    languageEnglish: 'English'
  },

  hero: {
    titleBanner: 'From family estates to digital assets. One trustee.',
    subheadline: 'Boutique Trust Services for Discerning Clients',
    value: 'We combine Traditional Values with Next Gen Execution'
  },

  aboutUs: {
    title: 'About',
    para1: 'Clients rarely arrive with a mandate already defined. They arrive with a question: how to protect what they have built, how to structure a life that spans borders, or how to ensure what they have created outlasts them.',
    para2: 'Lumen Advisory exists for that moment.',
    para3: 'We partner with internationally minded entrepreneurs, founders and families who need clarity before they need a product. As an independent trustee company based in Liechtenstein, we combine fiduciary and legal expertise to build structures that actually fit: asset protection, succession planning, relocation and family governance.',
    para4: 'With offices in Liechtenstein, Vienna and Kraków, we work where our clients live — particularly across Central and Eastern Europe.'
  },

  practiceAreas: {
    title: 'Practice Areas',
    familyOffice: 'Family Office',
    successionPlanning: 'Succession Planning',
    relocationServices: 'Relocation Services',
    philanthropy: 'Philanthropy',
    accounting: 'Accounting',
    legalAdvice: 'Legal Advice and Notarial Services'
  },

  partners: {
    title: 'Our Partners',
    remoName: 'Remo Mairhofer',
    remoTitle: 'Attorney-at-Law | Trustee | Founder & CEO',
    remoBio: 'M.A. HSG (Law), M.A. HSG (Banking and Finance)<br>LL.M., CII (Award)',
    tomaszName: 'Tomasz Klimek',
    tomaszTitle: 'Attorney-at-Law (FL, A & PL) | Notary Public | Partner',
    tomaszBio: 'LL.M.',
    viewProfile: 'View profile →'
  },

  partnersPage: {
    heroTitle: 'Our Partners',
    heroTagline: 'The people behind Lumen Advisory',
    linkedinTitle: 'Connect on LinkedIn',
    linkedinDesc: 'Follow Lumen Advisory for insights on asset protection, succession planning, and Liechtenstein law.',
    linkedinButton: 'Follow on LinkedIn',
    viewLinkedinProfile: 'View LinkedIn Profile'
  },

  contact: {
    title: 'Contact',
    getInTouch: 'Get in Touch',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    sendMessage: 'Send Message',
    ourOffices: 'Our Offices',
    officeSchaan: 'Office Schaan',
    schaanAddress1: 'Im Bretscha 7',
    schaanAddress2: 'FL-9494 Schaan',
    schaanCountry: 'Principality of Liechtenstein',
    schaanPhone: 'Phone +423 340 11 40',
    officeVienna: 'Office Vienna',
    viennaAddress1: 'Mahlerstraße 13/1B',
    viennaAddress2: 'A-1010 Vienna',
    viennaCountry: 'Austria',
    viennaPhone: 'Phone +43 1 904 31 34',
    officeKrakow: 'Office Krakow',
    krakowAddress1: 'ul. Kielecka 19',
    krakowAddress2: 'PL-31-523 Kraków',
    krakowCountry: 'Poland',
    krakowPhone: 'Phone +48 600 786 706'
  },

  footer: {
    practiceAreas: 'Practice Areas',
    partners: 'Partners',
    contact: 'Contact',
    copyright: '© 2026 Lumenadvisory. All rights reserved.',
    tagline: 'Independent Trustee Company\nLiechtenstein',
    navTitle: 'Navigation',
    officesTitle: 'Offices',
    membershipsTitle: 'Memberships',
    sitemap: 'Sitemap',
    privacyPolicy: 'Privacy Policy',
    imprint: 'Imprint'
  },

  sitemap: {
    heading: 'Sitemap',
    mainSection: 'Main',
    practiceAreasSection: 'Practice Areas',
    otherSection: 'Other',
    home: 'Home',
    about: 'About',
    ourPartners: 'Our Partners',
    faq: 'FAQ',
    contact: 'Contact',
    familyOffice: 'Family Office',
    successionPlanning: 'Succession Planning',
    relocationServices: 'Relocation Services',
    philanthropy: 'Philanthropy',
    accounting: 'Accounting',
    legalNotarial: 'Legal &amp; Notarial Services',
    clientLogin: 'Client Login'
  },

  privacyPolicy: {
    heading: 'Privacy Policy',
    section1Title: 'I. Name and address of the responsible person',
    section2Title: 'II. Data processing in general',
    section2Sub1Title: '1. Scope of the processing of personal data',
    section2Sub1Para: 'The processing of personal data is limited to data that is required to operate a functional website and for the provision of content and services. The processing of personal data of our users is based on the purposes agreed or on a legal basis (GDPR). We only collect personal data that is necessary to implement and process our tasks and services or if you provide data voluntarily.',
    section2Sub2Title: '2. Your rights (rights of the persons affected)',
    section2Sub2Para1: 'You have the right to request information about any of your personal data we process. In particular, you have the right to request information about the purpose of the processing, the categories of personal data, the categories of recipients who will have access or were disclosed with your data, the duration periods for saving the personal data, whether there is a right to adjust/correct, erase, restrict or object, transmission of data, the source of your data if not collected through us and if we use automatic decision-making technologies including profiling.',
    section2Sub2Para2: 'Additionally, you have the right to revoke a previously granted consent to use your personal data at any time.',
    section2Sub2Para3: 'If you believe that the processing of your personal data is inconsistent or contradicts the applicable data protection laws you have the possibility to lodge a complaint with the data protection office.',
    section3Title: 'III. Description and scope of data processing',
    section3Sub1Title: '1. Server log files',
    section3Sub1Para1: 'When you access our website, general information that is not related to a specific person is collected. This information (server log files) includes, for example, the type of web browser, the operating system used, the domain name of your Internet service provider.',
    section3Sub1Para2: 'This information is technically necessary in order to correctly deliver the content you have requested from websites and is mandatory when using the Internet. In particular, they are processed for the following purposes:',
    section3Sub1List: '<li>ensuring a trouble-free connection to the website,</li><li>ensuring the smooth use of our website,</li><li>evaluation of system safety and stability as well as</li><li>other administrative purposes.</li>',
    section3Sub1Para3: 'The processing of your personal data is based on our legitimate interest in the aforementioned purposes of data collection. We do not use your data to draw conclusions about your person. Recipients of the data are only the responsible body and, if applicable, the processor.',
    section3Sub1Para4: 'Anonymous information of this kind may be statistically evaluated by us in order to optimize our Internet presence and the technology.',
    section3Sub2Title: '2. Script libraries (Google Webfonts)',
    section3Sub2Para1: 'In order to present our content correctly and graphically appealing, we use script libraries and font libraries such as Google Webfonts (<a href="https://www.google.com/webfonts/" target="_blank" rel="noopener" style="color:var(--gold);text-decoration:none;">https://www.google.com/webfonts/</a>) on this website. Google Webfonts are transferred to your browser\'s cache to avoid multiple loading. If the browser does not support Google Webfonts or does not allow access, content will be displayed in a default font.',
    section3Sub2Para2: 'Calling script libraries or font libraries automatically triggers a connection to the library operator. It is theoretically possible — but currently also unclear whether and for what purposes — for the operators of such libraries to collect data.',
    section3Sub2Para3: 'The privacy policy of the library operator Google can be found here: <a href="https://www.google.com/policies/privacy/" target="_blank" rel="noopener" style="color:var(--gold);text-decoration:none;">https://www.google.com/policies/privacy/</a>',
    section3Sub3Title: '3. Cookies',
    section3Sub3Para1: 'This website uses cookies to make our services more user-friendly, more effective and safer. A cookie is a small text file that we place in the browser\'s cookie file on the hard disk of your computer when you visit our website. It enables our website to recognise you as a user when a connection between our web server and your browser is established.',
    section3Sub3Para2: 'You can configure your browser: to inform you each time a cookie is to be saved and allow only certain cookies, to refuse to accept cookies in certain cases or in general, or to automatically delete any cookies when the browser is closed. Full functioning of this website can be impaired if you generally deactivate cookies.',
    section3Sub4Title: '4. Contact with us',
    section3Sub4Para: 'If you contact us via e-mail, the data you provide will be stored by us for the purpose of processing the enquiry and possible follow-up questions.',
    section4Title: 'IV. Data security',
    section4Para1: 'We use a common encryption technology (SSL — Secure Socket Layer) in connection with the highest encryption levels that are supported by your browser. If a page on our website was/is being transmitted encrypted it is shown by the lock symbol in the address bar of your browser.',
    section4Para2: 'Additionally, we use appropriate technical and organizational security measures to protect your data from accidental or intentional manipulation, partial or complete loss, destruction, or to prevent unauthorized access by third parties. Our security measures are continuously upgraded according to the latest technological developments.'
  },

  imprint: {
    heading: 'Imprint',
    responsibleTitle: 'Responsible for the content',
    conceptTitle: 'Concept, design and implementation',
    conceptContent: 'Lumen Advisory',
    contentTitle: 'Content of the online offer',
    contentPara: 'The author reserves the right not to be responsible for the topicality, correctness, completeness or quality of the information provided. Liability claims against the author, which refer to material or immaterial nature, which were caused by the use or disuse of the information provided or by the use of incorrect and incomplete information, are excluded, unless the author proves intentional or grossly negligent fault is present. All offers are non-binding. The author expressly reserves the right to change, supplement or delete parts of the pages or the entire offer without prior notice or to stop the publication temporarily or permanently.',
    referencesTitle: 'References and links',
    referencesPara1: 'In direct or indirect references to external websites ("hyperlinks"), which lie outside the area of responsibility of the author, a liability obligation would come into force only in the case in which the author has knowledge of the contents and it would be technically possible and reasonable to prevent the use in case of illegal content. The author hereby expressly declares that at the time of linking, no illegal content was recognizable on the linked pages. The author has no influence on the current and future design, content or authorship of the linked pages. Therefore he dissociates himself hereby expressly from all contents of all linked/linked sides, which were changed after the link setting.',
    referencesPara2: 'This statement applies to all links and references within the own Internet offer as well as to foreign entries in guest books, discussion forums, link directories, mailing lists and in all other forms of databases on whose contents external write accesses are possible. For illegal, incorrect or incomplete contents and in particular for damages resulting from the use or non-use of such information presented, the provider of the page referred to, and not the one who only links to the respective publication, is liable.',
    copyrightTitle: 'Copyright and Trademark Law',
    copyrightPara: 'The author endeavors to observe the copyrights of the images, graphics, sound documents, video sequences and texts used in all publications, to use images, graphics, sound documents, video sequences and texts created by himself or to resort to license-free graphics, sound documents, video sequences and texts. All brand names and trademarks mentioned within the Internet offer and possibly protected by third parties are subject without restriction to the provisions of the respectively valid trademark law and the ownership rights of the respective registered owners. Just because of the mere mention is not to draw the conclusion that trademarks are not protected by rights of third parties! The copyright for published, created by the author objects remains solely with the author of the pages. Reproduction or use of such graphics, sound documents, video sequences and texts in other electronic or printed publications is not permitted without the express consent of the author.',
    pictureCreditsTitle: 'Picture Credits',
    pictureCreditsPara: 'Church Schaan by wgauthier is licensed under CC BY-SA 2.0. Original source via <a href="https://flickr.com/photos/59442036@N08/34920952374" target="_blank" rel="noopener" style="color:var(--gold);text-decoration:none;">Flickr</a>.'
  },

  insightsPage: {
    remoName: 'Remo Mairhofer',
    remoTitle: 'Attorney-at-Law | Trustee | Founder & CEO',
    remoBio1: 'Remo Mairhofer is an Attorney-at-Law and licensed trustee, serving as Founder and CEO of LUMEN ADVISORY Trust reg. and founder of Mairhofer Advokatur in Liechtenstein. His work focuses on the establishment, governance, and ongoing supervision of trust and foundation structures, advising intermediaries and private clients in cross-border structures.',
    remoBio2: 'He holds degrees in Law and Banking & Finance from the University of St. Gallen and an LL.M. from the University of Sydney. He is admitted to the Liechtenstein Bar, has completed the Liechtenstein trustee examinations, and serves as a Substitute Judge at the Constitutional Court of Liechtenstein.',
    tomaszName: 'Dr. Tomasz Klimek',
    tomaszTitle: 'Attorney-at-Law (FL, A & PL) | Notary Public | Partner',
    tomaszBio1: 'Dr. Tomasz Klimek is a Public Notary and Attorney-at-Law in Liechtenstein and a partner at Mairhofer Advokatur. He advises on and oversees legally complex fiduciary and corporate structures, with a particular focus on cross-border foundations, holding entities, and asset-holding arrangements involving Liechtenstein, Austria, and Poland.',
    tomaszBio2: 'Dr. Klimek holds a Doctor of Laws from the University of Vienna and multiple LL.M. degrees in company, foundation, and trust law. He is admitted to the bar in Liechtenstein, Austria, and Poland and is the only Polish-speaking attorney in Liechtenstein, allowing him to bridge jurisdictions with precision and accountability.',
    servicesTitle: 'Our Services',
    familyOfficeTitle: 'Family Office',
    familyOfficePara1: 'Complex wealth requires a single point of clarity.',
    familyOfficePara2: 'We act as the central coordination layer for clients whose holdings span traditional structures and digital asset ecosystems — aligning trusteeship, corporate governance, custodial arrangements, and advisor relationships so that decisions remain consistent, documented, and in control regardless of how many jurisdictions or asset classes are involved.',
    successionPlanningTitle: 'Succession Planning',
    successionPlanningPara1: 'Succession is not a single event — it is a structure built to hold over time.',
    successionPlanningPara2: 'We design succession solutions that account for the full picture of modern wealth, from business interests and real estate to cryptocurrency portfolios and digital asset collections. Each mandate is built to remain legally robust and enforceable across jurisdictions, with governance rules, custodial arrangements, and access protocols that ensure nothing is lost or frozen at the moment it matters most.',
    relocationServicesTitle: 'Relocation Services',
    relocationServicesPara1: 'Relocation changes more than your address — it can reshape how your entire wealth picture is seen.',
    relocationServicesPara2: 'Moving jurisdiction affects how assets are taxed, how existing structures are interpreted by new authorities, and — for holders of digital assets — can trigger consequences that are rarely anticipated. We review wallet structures, DeFi positions, staking arrangements, and existing Liechtenstein foundations or trusts in parallel, ensuring the transition is compliant, tax-efficient, and complete.',
    philanthropyTitle: 'Philanthropy',
    philanthropyPara1: 'Generosity deserves the same rigour as any other form of wealth stewardship.',
    philanthropyPara2: 'We help clients translate philanthropic intent into durable structure — establishing Liechtenstein charitable foundations that accept traditional and digital assets, govern cross-border grant-making with full legal transparency, and are built to operate across generations rather than news cycles. This includes navigating the regulatory and reporting requirements that allow philanthropic capital — in any form — to move across borders cleanly and reach its intended purpose.',
    accountingTitle: 'Accounting',
    accountingPara1: 'Within a fiduciary structure, reporting is not a formality — it is a control function.',
    accountingPara2: 'We provide consolidated accounting that covers both conventional holdings and digital asset activity, including on-chain positions, staking rewards, and token allocations, alongside traditional shareholdings and financial instruments. The result is a single reporting framework that satisfies trustee oversight, regulatory requirements, and the specific accounting treatment applicable across multiple jurisdictions.',
    legalAdviceTitle: 'Legal Advice & Notarial Services',
    legalAdvicePara1: 'Sound structures require more than good design — they require precise execution.',
    legalAdvicePara2: 'Our legal and notarial services are integrated directly into fiduciary mandates, ensuring that frameworks covering both conventional and digital assets are properly documented, executed, and maintained over time. This includes the legal structuring of foundations and holding entities for tokenized assets and crypto portfolios, with attention to custody arrangements, cross-border enforceability, and the governance requirements that keep complex structures intact.',
    publicationsTitle: 'Publications',
    publicationsIntro: 'We regularly publish articles and specialist papers on current topics that matter in and for our field — covering areas such as asset protection, succession law, cross-border structuring, and regulatory developments in Liechtenstein and beyond.',
    whitepaperDesc: 'Russia Sanctions — A comprehensive overview of the current legal framework and practical implications.',
    downloadButton: 'Download Whitepaper (PDF)',
    blogTitle: 'Blog',
    blogDesc: 'Our blog offers perspectives on wealth, legacy, and structure that matter today and shape tomorrow.',
    newsletterTagline: 'A monthly note on what quietly changes—and why it matters.',
    newsletterPlaceholder: 'Enter your email',
    newsletterButton: 'Newsletter'
  },

  faq: {
    title: 'FAQ',
    faq1q: 'Why Lumen Advisory, and what does it cost?',
    faq1a: 'We are an independent trustee company. Our fees are scope-based and agreed at the outset of each mandate. We earn no commissions on products, funds, or investments. What that means in practice: the advice you receive is shaped by your structure, not by what generates revenue for us. For clients with significant wealth across borders, that independence, combined with our legal and fiduciary expertise under one roof, is what most single-jurisdiction advisors cannot offer.',
    faq2q: 'What makes a Liechtenstein structure the right choice?',
    faq2a: 'Liechtenstein is the only jurisdiction in the world that combines Anglo-American trust law with European civil law. Your structure carries the flexibility of both traditions within a single, coherent framework. Its foundation law dates to 1926. It sits within the European Economic Area, holds a AAA sovereign rating, and appears on no grey list. Banks and regulatory authorities recognise Liechtenstein structures without friction, wherever you operate. For internationally minded clients, that recognition is not a nice-to-have. It is the point.',
    faq3q: 'What kind of clients do you work with?',
    faq3a: 'Founders, entrepreneurs, and multi-generational families with assets, interests, or family members across multiple jurisdictions. Typically clients who have already built something substantial and now need it governed properly, not advised ad hoc. Many come to us during a transition: a business exit, a relocation, a succession conversation that has become urgent. They come because they have a specific question that their existing advisors have not fully answered.',
    faq4q: 'How do you manage mandates across multiple countries and time zones?',
    faq4a: 'Most of our clients are not based in Liechtenstein. We operate primarily across Central and Eastern Europe, with offices in Schaan, Vienna, and Kraków, and advise clients internationally. The structure is domiciled in Liechtenstein; the relationship is built where the client lives. Mandates are managed with defined reporting cadences, documented governance, and direct partner access, not delegated to junior staff.',
    faq5q: 'What does the first conversation look like?',
    faq5a: 'It is a conversation, not a pitch. We take time to understand your situation: your existing structures, your goals, and where complexity has built up. If there is a clear fit, we scope a first engagement together: a structural review, a specific transaction, or an ongoing advisory mandate. We do not propose solutions before we understand the question.'
  },

  familyOfficePage: {
    title: 'Family Office Services',
    meta: 'Independent family office services from Liechtenstein. Lumen Advisory coordinates trustees, advisors and custodians across borders for entrepreneurs and multi-generational families.',
    bulletsTitle: 'What We Do',
    bullet1: 'Acting as sole coordination point between trustees, legal counsel, asset managers, and custodians across all relevant jurisdictions',
    bullet2: 'Designing governance frameworks that cover both conventional and digital asset classes within a single, coherent structure',
    bullet3: 'Preparing consolidated financial reporting across all holdings — on-chain and off-chain — to a standard suitable for trustees and regulators',
    bullet4: 'Establishing family council structures with documented decision-making protocols, defined roles, and succession triggers',
    bullet5: 'Monitoring structural integrity over time, including responses to regulatory changes, advisor transitions, and evolving family circumstances',
    whoForTitle: 'Who This Is For',
    whoFor1Label: 'The Founder',
    whoFor1: 'You\'ve built significant wealth across borders and need a single, trusted point of coordination — not another advisor operating in isolation.',
    whoFor2Label: 'The Multi-Generational Family',
    whoFor2: 'Your wealth involves multiple family members, advisors, and jurisdictions. You need governance that holds it together across generations.',
    whoFor3Label: 'The Complex Portfolio Holder',
    whoFor3: 'Your assets span private equity, real estate, and digital holdings. You need oversight that treats all of it with equal rigour.',
    faq1q: 'What does a Liechtenstein trustee do in a family office structure?',
    faq1a: 'A Liechtenstein trustee acts as the legally accountable steward of the structure — holding assets, enforcing governance rules, coordinating advisors, and ensuring continuity. In a family office context, we extend this role to cover reporting, decision documentation, and long-term family governance.',
    faq2q: 'Can a family office structure manage both traditional and digital assets?',
    faq2a: 'Yes. We work with structures that combine conventional assets — real estate, equity stakes, private equity — with digital assets such as cryptocurrency portfolios, DeFi positions, and tokenised holdings. Unified governance and consolidated reporting is applied across all asset classes.',
    faq3q: 'How do you handle families based in multiple countries?',
    faq3a: 'Our team works across Liechtenstein, Austria, and Poland and advises on structures that span multiple jurisdictions. We coordinate with local advisors and ensure that the overarching governance structure remains coherent regardless of where family members live or where assets are held.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If you are looking for a coordinated approach to complex, cross-border wealth — we would like to hear from you.',
    ctaButton: 'Get in Touch'
  },

  successionPlanningPage: {
    title: 'Succession Planning',
    meta: 'Succession planning for entrepreneurs and families in Liechtenstein and across Europe. Asset protection, foundation structures, and cross-border continuity — including digital assets.',
    bulletsTitle: 'What We Do',
    bullet1: 'Structuring the transfer of business interests, real estate, and investment portfolios into Liechtenstein foundations or trust arrangements',
    bullet2: 'Designing succession rules that explicitly address digital assets — including private key access, wallet governance, and custodial handover procedures',
    bullet3: 'Building multi-generational continuity frameworks with clear distribution rules, governance protocols, and family oversight mechanisms',
    bullet4: 'Protecting against forced heirship claims and cross-border legal conflicts through jurisdictional structuring and timely legal documentation',
    bullet5: 'Coordinating with tax advisors and legal counsel across relevant jurisdictions to ensure each succession step is executed without triggering avoidable tax events',
    whoForTitle: 'Who This Is For',
    whoFor1Label: 'The Business Owner',
    whoFor1: 'You\'ve built a company and need it to transfer cleanly — to family, a foundation, or the next generation — without ambiguity or legal conflict.',
    whoFor2Label: 'The Intermediary',
    whoFor2: 'You act on behalf of clients whose assets require structured succession — ensuring that access, governance, and continuity are secured independently of any single person or relationship.',
    whoFor3Label: 'The Family Planner',
    whoFor3: 'You are thinking across generations and need structures that protect your family from forced heirship rules, cross-border disputes, and frozen estates.',
    faq1q: 'Can a Liechtenstein foundation protect assets from forced heirship rules?',
    faq1a: 'Liechtenstein foundations can provide significant protection against forced heirship claims under foreign law, depending on the applicable jurisdiction and the structure of the foundation. This is a fact-specific analysis and we assess each client\'s situation individually before recommending a structure.',
    faq2q: 'What happens to crypto and digital assets when there is no succession plan?',
    faq2a: 'Without proper planning, digital assets can become inaccessible or lost entirely. Private keys may be unknown to heirs, wallet access may be tied to single devices, and legal frameworks for claiming digital assets vary widely. We build succession structures that specifically address key access, custodial arrangements, and wallet governance.',
    faq3q: 'When is the right time to start succession planning?',
    faq3a: 'Earlier than most people expect. Succession planning is most effective when designed alongside the asset structure itself — not as an afterthought when assets are already scattered. If you have meaningful wealth across more than one country, the time to plan is now.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'Succession planning works best when started early. If you want to understand your options, we are ready to have that conversation.',
    ctaButton: 'Get in Touch'
  },

  relocationPage: {
    title: 'Relocation Services',
    meta: 'Relocation services for entrepreneurs and investors moving to or from Liechtenstein, Austria, and Central Europe. Tax structuring, foundation review, and cross-border compliance.',
    bulletsTitle: 'What We Do',
    bullet1: 'Reviewing and restructuring existing foundations, trusts, and holding companies ahead of a change of residence to prevent unintended tax consequences',
    bullet2: 'Conducting exit tax analysis under the applicable home-country rules and identifying mitigation strategies before the move takes effect',
    bullet3: 'Advising on Liechtenstein and Austrian residence structures, including eligibility conditions, tax treatment, and interaction with existing wealth structures',
    bullet4: 'Analysing how the destination country will treat distributions, income, and held assets — including cryptocurrency portfolios and digital holdings',
    bullet5: 'Coordinating the legal and documentation steps required across all affected jurisdictions to ensure the transition is clean, compliant, and properly timed',
    whoForTitle: 'Who This Is For',
    whoFor1Label: 'The Relocating Entrepreneur',
    whoFor1: 'You are moving to or from Central Europe and your existing structures — foundations, companies, trusts — need to be reviewed before your residency changes.',
    whoFor2Label: 'The Mobile Professional',
    whoFor2: 'You are internationally mobile, holding assets in multiple countries, and need advice that matches the complexity of your actual situation.',
    whoFor3Label: 'The Exit Planner',
    whoFor3: 'You are leaving a high-tax jurisdiction and need a clear analysis of exit tax exposure and how your existing structures should be adjusted.',
    faq1q: 'Does relocation affect my existing Liechtenstein foundation?',
    faq1a: 'It can. Changing your residence can affect how your home country — and your destination country — views and taxes distributions from a Liechtenstein foundation. We review the structural implications before the move and adjust the governance documentation where necessary.',
    faq2q: 'What are the tax implications of moving to Liechtenstein?',
    faq2a: 'Liechtenstein has a favourable and stable tax environment. Residency can be structured in ways that are tax-efficient for international clients, particularly those with existing Liechtenstein trust or foundation structures. Each situation depends on the source of income, existing structures, and applicable double-tax treaties.',
    faq3q: 'How early should I plan a relocation?',
    faq3a: 'Ideally six to twelve months before the intended move date. Structural adjustments, legal documentation, and tax analysis take time to do properly. Last-minute relocations often lead to avoidable tax events or compliance gaps that are difficult to correct retroactively.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If you are planning a move across borders and want to ensure your structures are ready, we can help you prepare.',
    ctaButton: 'Get in Touch'
  },

  philanthropyPage: {
    title: 'Philanthropic Structures',
    meta: 'Philanthropic foundations and charitable structures established in Liechtenstein. Lumen Advisory helps clients channel wealth into impact — with full legal transparency and governance.',
    bulletsTitle: 'What We Do',
    bullet1: 'Establishing and registering Liechtenstein charitable foundations under the PGR, including drafting statutes, purpose definitions, and governance documents',
    bullet2: 'Structuring cross-border grant-making programmes with clear eligibility criteria, disbursement controls, and documentation suited to regulatory scrutiny',
    bullet3: 'Setting up philanthropic vehicles capable of accepting and deploying both traditional and digital asset donations, including cryptocurrencies and tokenised instruments',
    bullet4: 'Implementing ongoing compliance, annual reporting, and governance oversight to ensure the foundation operates within its defined purpose and legal obligations',
    bullet5: 'Advising on the strategic alignment of philanthropic structures with existing family or business wealth, including interaction with private foundations and holding entities',
    whoForTitle: 'Who This Is For',
    whoFor1Label: 'The Impact Entrepreneur',
    whoFor1: 'You\'ve achieved financial success and want your giving to be as structured and intentional as your business — with real governance and long-term integrity.',
    whoFor2Label: 'The Legacy Builder',
    whoFor2: 'Your family wants to give across generations, and you need a structure that survives the founders and continues to deliver according to your values.',
    whoFor3Label: 'The Digital Philanthropist',
    whoFor3: 'You hold crypto or digital assets and want to deploy them philanthropically in a compliant, organised, and impactful way.',
    faq1q: 'What is a Liechtenstein charitable foundation?',
    faq1a: 'A Liechtenstein charitable foundation is a legally independent entity established to pursue specific public benefit purposes. It is governed by the Liechtenstein Persons and Companies Act (PGR) and can hold a wide range of assets. It is recognised internationally and can operate cross-border grant-making activities.',
    faq2q: 'Can a foundation accept cryptocurrency donations?',
    faq2a: 'Yes. We structure philanthropic vehicles that can accept and hold digital assets, including cryptocurrencies and tokenised instruments, alongside conventional assets. The foundation\'s statutes and governance documentation are designed to accommodate digital asset inflows and outflows in a legally compliant manner.',
    faq3q: 'How is a charitable foundation different from a private foundation?',
    faq3a: 'A charitable foundation is established for public benefit purposes and its assets are permanently dedicated to those purposes. A private foundation, by contrast, may serve private beneficiaries. The distinction affects tax treatment, governance requirements, and the permanence of the dedication of assets.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If you want to give with structure and impact, we can help you build the right vehicle.',
    ctaButton: 'Get in Touch'
  },

  accountingPage: {
    title: 'Accounting & Reporting',
    meta: 'Accounting and financial reporting for Liechtenstein foundations, trusts, and cross-border structures. Consolidated statements covering traditional and digital assets.',
    bulletsTitle: 'What We Do',
    bullet1: 'Preparing consolidated annual financial statements for Liechtenstein foundations, trusts, and holding companies that span multiple jurisdictions and asset classes',
    bullet2: 'Recording and valuing digital asset holdings — including cryptocurrencies, DeFi positions, staking rewards, and NFT transactions — as part of the overall financial picture',
    bullet3: 'Producing regulatory compliance reports tailored to the reporting obligations applicable to each specific fiduciary structure and jurisdiction',
    bullet4: 'Maintaining audit-ready bookkeeping with full supporting documentation, ensuring accounts are accurate, traceable, and suitable for third-party review',
    bullet5: 'Coordinating with appointed auditors, tax advisors, and trustees to provide complete financial documentation when required by regulation or client preference',
    whoForTitle: 'Who This Is For',
    whoFor1Label: 'The Foundation Trustee',
    whoFor1: 'You oversee a Liechtenstein foundation holding both traditional investments and digital assets, and need reporting that satisfies trustees, regulators, and auditors alike.',
    whoFor2Label: 'The Multi-Jurisdiction Owner',
    whoFor2: 'Your assets span multiple countries and legal forms. You need one consolidated picture, not fragmented statements from separate advisors.',
    whoFor3Label: 'The Digital Asset Holder',
    whoFor3: 'Your portfolio includes significant cryptocurrency positions, on-chain activity, or tokenised holdings alongside conventional assets. You need a single consolidated picture, not separate statements, and accounting treatment that holds up to trustee and regulatory scrutiny across jurisdictions.',
    faq1q: 'What does accounting for a Liechtenstein foundation involve?',
    faq1a: 'Liechtenstein foundations are required to maintain proper accounting records and, depending on their size and activities, may be subject to audit requirements. We prepare annual accounts, manage bookkeeping, and ensure that the foundation\'s financial records are accurate, compliant, and suitable for trustee oversight.',
    faq2q: 'How do you handle reporting for crypto holdings and DeFi positions?',
    faq2a: 'We treat digital asset holdings as part of the consolidated financial picture. This includes recording on-chain transactions, valuing cryptocurrency positions, accounting for DeFi yields and staking rewards, and applying appropriate accounting treatment across jurisdictions. Reporting is tailored to the applicable regulatory and trustee requirements.',
    faq3q: 'Do you provide audit support?',
    faq3a: 'Yes. We prepare accounts and supporting documentation to a standard that supports third-party audit. Where audit is required — either by regulation or by client preference — we coordinate with the appointed auditor and provide full documentation of the accounting basis used.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If your structures have outgrown basic bookkeeping and you need accurate, cross-border financial reporting, we can help.',
    ctaButton: 'Get in Touch'
  },

  legalNotarialPage: {
    title: 'Legal & Notarial Services',
    meta: 'Legal advice and notarial services for foundations, trusts, and cross-border structures in Liechtenstein. Execution, supervision, and structuring by licensed attorneys and notaries.',
    bulletsTitle: 'What We Do',
    bullet1: 'Establishing and registering foundations, trusts, and holding companies under Liechtenstein law, with full notarial execution of all founding documents',
    bullet2: 'Drafting and executing cross-border legal agreements, powers of attorney, and transactional documents with legal validity across multiple jurisdictions',
    bullet3: 'Providing legal structuring for tokenised assets, digital holdings, and smart contract governance within Liechtenstein-based entities',
    bullet4: 'Supervising existing fiduciary structures on an ongoing basis — reviewing statutes, advising on regulatory changes, and executing any required structural amendments',
    bullet5: 'Coordinating legal formalities across Liechtenstein, Austria, and Poland, with access to trusted local counsel in further jurisdictions where required',
    whoForTitle: 'Who This Is For',
    whoFor1Label: 'The International Structurer',
    whoFor1: 'You are establishing or restructuring foundations, trusts, or holding companies across jurisdictions and need legally precise, notarially valid execution.',
    whoFor2Label: 'The Digital Asset Client',
    whoFor2: 'Your holdings include tokenised assets or crypto that require legal frameworks not yet offered by most conventional legal practices.',
    whoFor3Label: 'The Cross-Border Family',
    whoFor3: 'You need agreements, estate documents, or corporate structures that will hold legal weight in multiple countries simultaneously.',
    faq1q: 'Why do I need a notary for a Liechtenstein foundation?',
    faq1a: 'Under Liechtenstein law, the establishment of certain legal entities — including foundations — requires notarial execution of the founding documents. A notary verifies the identity of the parties, certifies the legal validity of the documents, and ensures compliance with formal requirements. Dr. Tomasz Klimek is a licensed notary in Liechtenstein.',
    faq2q: 'Can you execute documents across multiple jurisdictions?',
    faq2a: 'Yes. Our team is admitted to practice in Liechtenstein, Austria, and Poland. For cross-border matters involving other jurisdictions, we coordinate with trusted local counsel. We are experienced in managing the legal formalities required when documents must be valid in more than one country.',
    faq3q: 'What is the role of a Liechtenstein attorney in a foundation structure?',
    faq3a: 'A Liechtenstein attorney ensures that the foundation\'s statutes, governance documents, and operational decisions remain legally sound and enforceable. This includes reviewing beneficiary arrangements, advising on regulatory obligations, and supervising any structural changes over time.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If you need legally sound execution for a complex cross-border structure, our team is ready to help.',
    ctaButton: 'Get in Touch'
  }
};
