export const en = {
  header: {
    more: 'More ▾',
    whoWeAre: 'Who We Are',
    whatWeDo: 'What We Do',
    practiceAreas: 'Practice Areas',
    partners: 'Partners',
    contact: 'Contact',
    insights: 'Insights',
    clientLogin: 'Client Login',
    languageDeutsch: 'Deutsch',
    languageEnglish: 'English'
  },

  hero: {
    titleBanner: 'From family estates to digital assets. One trustee',
    subheadline: 'Boutique Trust Services for Discerning Clients',
    value: 'We combine Traditional Values with Next Gen Execution'
  },

  aboutUs: {
    title: 'About',
    para1: 'Most people don\'t start by looking for a trustee. They start with a question — how to protect what they\'ve built, how to structure a cross-border life, or how to ensure what they\'ve created outlasts them.',
    para2: 'Lumen Advisory exists for that moment.',
    para3: 'We partner with internationally minded entrepreneurs, founders and families — often self-made, often operating across multiple jurisdictions — who need clarity before they need a product.',
    para4: 'As an independent trustee company based in Liechtenstein, we combine fiduciary expertise with legal and notarial experience to build structures that actually fit: asset protection, succession planning, relocation and long-term family governance.',
    para5: 'Our team brings international backgrounds and direct involvement to every mandate. With offices in Liechtenstein, Vienna and Kraków, we work where our clients live and operate — particularly across Central and Eastern Europe.'
  },

  practiceAreas: {
    title: 'Practice Areas',
    familyOffice: 'Family Office',
    successionPlanning: 'Succession Planning',
    relocationServices: 'Relocation Services',
    philanthropy: 'Philanthropy',
    accounting: 'Accounting',
    legalAdvice: 'Legal Advice and Notarial Services'
  },

  partners: {
    title: 'Our Partners',
    remoName: 'Remo Mairhofer',
    remoTitle: 'Attorney at Law (FL) | Substitute Notary',
    remoBio: 'M.A. HSG (Law), M.A. HSG (Banking and Finance)<br>LL.M., CII (Award)',
    tomaszName: 'Dr. iur. Tomasz Klimek',
    tomaszTitle: 'Attorney at Law (FL, A and PL) | Notary Public',
    tomaszBio: 'LL.M.'
  },

  contact: {
    title: 'Contact & Offices',
    getInTouch: 'Get in Touch',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    sendMessage: 'Send Message',
    ourOffices: 'Our Offices',
    officeSchaan: 'Office Schaan',
    schaanAddress1: 'Im Bretscha 7',
    schaanAddress2: 'FL-9494 Schaan',
    schaanPhone: 'Phone +423 340 11 40',
    officeVienna: 'Office Vienna',
    viennaAddress1: 'Mahlerstraße 13/1B',
    viennaAddress2: 'A-1010 Vienna',
    viennaPhone: 'Phone +43 1 904 31 34',
    officeKrakow: 'Office Krakow',
    krakowAddress1: 'ul. Kielecka 19',
    krakowAddress2: 'PL-31-523 Kraków',
    krakowPhone: 'Phone +43 1 904 31 34'
  },

  footer: {
    practiceAreas: 'Practice Areas',
    partners: 'Partners',
    contact: 'Contact',
    copyright: '© 2026 Lumenadvisory. All rights reserved.'
  },

  insightsPage: {
    remoName: 'Remo Mairhofer',
    remoTitle: 'Attorney-at-Law | Trustee | Founder & CEO',
    remoBio1: 'Remo Mairhofer is an Attorney-at-Law and licensed trustee, serving as Founder and CEO of LUMEN ADVISORY Trust reg. and founder of Mairhofer Advokatur in Liechtenstein. His work focuses on the establishment, governance, and ongoing supervision of trust and foundation structures, advising intermediaries and private clients in cross-border structures.',
    remoBio2: 'He holds degrees in Law and Banking & Finance from the University of St. Gallen and an LL.M. from the University of Sydney. He is admitted to the Liechtenstein Bar, has completed the Liechtenstein trustee examinations, and serves as a Substitute Judge at the Constitutional Court of Liechtenstein.',
    tomaszName: 'Dr. Tomasz Klimek',
    tomaszTitle: 'Public Notary | Attorney-at-Law | Partner',
    tomaszBio1: 'Dr. Tomasz Klimek is a Public Notary and Attorney-at-Law in Liechtenstein and a partner at Mairhofer Advokatur. He advises on and oversees legally complex fiduciary and corporate structures, with a particular focus on cross-border foundations, holding entities, and asset-holding arrangements involving Liechtenstein, Austria, and Poland.',
    tomaszBio2: 'Dr. Klimek holds a Doctor of Laws from the University of Vienna and multiple LL.M. degrees in company, foundation, and trust law. He is admitted to the bar in Liechtenstein, Austria, and Poland and is the only Polish-speaking attorney in Liechtenstein, allowing him to bridge jurisdictions with precision and accountability.',
    servicesTitle: 'Our Services',
    familyOfficeTitle: 'Family Office',
    familyOfficePara1: 'We act as a single point of coordination for complex wealth that no longer fits neatly into one category. Today that means aligning trusteeship, corporate holdings, digital asset custodians, and advisors across both traditional and on-chain structures—so that decisions remain clear, documented, and consistent over time.',
    familyOfficePara2: 'In practice, this can involve a founder whose wealth spans a Liechtenstein foundation holding equity stakes, a portfolio of cryptocurrencies and DeFi positions, and a collection of high-value digital art—where governance rules, reporting lines, and custodial oversight need to work seamlessly across very different asset classes and legal environments.',
    successionPlanningTitle: 'Succession Planning',
    successionPlanningPara1: 'Succession planning is rarely about a single transfer; it is about control, protection, and continuity over many years. We structure succession solutions that cover both conventional and digital wealth—from business interests and real estate to crypto holdings and NFT collections—remaining legally robust and enforceable across jurisdictions.',
    successionPlanningPara2: 'A typical mandate may involve a technology founder transferring equity, a cryptocurrency portfolio, and digital art holdings into a Liechtenstein foundation—with clear succession rules covering private key access, custodial arrangements, and wallet governance—ensuring nothing is lost or frozen at the moment of transition.',
    relocationServicesTitle: 'Relocation Services',
    relocationServicesPara1: 'Relocation affects more than residency—it often transforms how your assets are taxed and how your existing structures are viewed by new authorities. For holders of digital assets, this can trigger unexpected consequences depending on the destination country\'s treatment of crypto, NFTs, and token income.',
    relocationServicesPara2: 'When a crypto entrepreneur relocates from Germany to a more favourable jurisdiction, existing wallet structures, DeFi positions, and staking arrangements need to be reviewed alongside any Liechtenstein trust or foundation—ensuring the move is tax-efficient, compliant, and that no digital asset is inadvertently subject to exit taxation.',
    philanthropyTitle: 'Philanthropy',
    philanthropyPara1: 'Philanthropy works best when generosity is paired with structure. We help clients establish philanthropic vehicles that accept and deploy both traditional and digital wealth—including crypto donations and NFT proceeds—while meeting regulatory and governance standards.',
    philanthropyPara2: 'This may include setting up a Liechtenstein charitable foundation that receives cryptocurrency donations or NFT sale proceeds and channels them into educational or social projects abroad—with full legal transparency, compliant cross-border flows, and governance designed for long-term impact.',
    accountingTitle: 'Accounting',
    accountingPara1: 'Accounting within fiduciary structures is not just about numbers—it is about control and traceability. For clients with digital asset holdings, we provide reporting that covers on-chain and off-chain activity—including DeFi positions, staking rewards, NFT transactions, and token allocations—alongside conventional assets.',
    accountingPara2: 'A common scenario involves a Liechtenstein foundation holding both traditional shareholdings and a managed crypto portfolio, requiring consolidated reporting that satisfies trustee oversight, regulatory scrutiny, and the specific accounting treatment applicable to digital asset classes across multiple jurisdictions.',
    legalAdviceTitle: 'Legal Advice & Notarial Services',
    legalAdvicePara1: 'Legal advice and notarial services are fully integrated into our fiduciary work, ensuring that structures covering both conventional and digital assets are not only well designed but also properly executed and maintained.',
    legalAdvicePara2: 'This increasingly includes the legal structuring of foundations or companies that hold tokenized assets, NFT collections, or crypto portfolios alongside traditional real estate and equity—requiring legally sound frameworks for custody arrangements, smart contract governance, and cross-border digital asset transactions.',
    whitepaperTitle: 'Whitepaper',
    whitepaperDesc: 'Sanktionen Russland - Ein umfassender Überblick über die aktuellen rechtlichen Rahmenbedingungen und praktischen Implikationen.',
    downloadButton: 'Download Whitepaper (PDF)',
    blogTitle: 'Blog',
    blogDesc: 'Our blog offers perspectives on wealth, legacy, and structure that matter today and shape tomorrow.',
    newsletterTagline: 'A monthly note on what quietly changes—and why it matters.',
    newsletterPlaceholder: 'Enter your email',
    newsletterButton: 'Newsletter'
  },

  faq: {
    title: 'FAQ',
    comingSoon: 'Frequently asked questions coming soon.'
  },

  familyOfficePage: {
    title: 'Family Office Services',
    meta: 'Independent family office services from Liechtenstein. Lumen Advisory coordinates trustees, advisors and custodians across borders for entrepreneurs and multi-generational families.',
    bulletsTitle: 'What We Do',
    bullet1: 'Single coordination point across trustees, advisors, and custodians',
    bullet2: 'Governance frameworks for traditional and digital asset classes',
    bullet3: 'Cross-border consolidated reporting and oversight',
    bullet4: 'Family council structures and long-term governance protocols',
    whoForTitle: 'Who This Is For',
    whoFor: 'Entrepreneurs, founders, and multi-generational families whose wealth spans several jurisdictions, asset classes, or advisors — and who need a single, accountable point of coordination rather than another isolated product.',
    faq1q: 'What does a Liechtenstein trustee do in a family office structure?',
    faq1a: 'A Liechtenstein trustee acts as the legally accountable steward of the structure — holding assets, enforcing governance rules, coordinating advisors, and ensuring continuity. In a family office context, we extend this role to cover reporting, decision documentation, and long-term family governance.',
    faq2q: 'Can a family office structure manage both traditional and digital assets?',
    faq2a: 'Yes. We work with structures that combine conventional assets — real estate, equity stakes, private equity — with digital assets such as cryptocurrency portfolios, DeFi positions, and tokenised holdings. Unified governance and consolidated reporting is applied across all asset classes.',
    faq3q: 'How do you handle families based in multiple countries?',
    faq3a: 'Our team works across Liechtenstein, Austria, and Poland and advises on structures that span multiple jurisdictions. We coordinate with local advisors and ensure that the overarching governance structure remains coherent regardless of where family members live or where assets are held.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If you are looking for a coordinated approach to complex, cross-border wealth — we would like to hear from you.',
    ctaButton: 'Get in Touch'
  },

  successionPlanningPage: {
    title: 'Succession Planning',
    meta: 'Succession planning for entrepreneurs and families in Liechtenstein and across Europe. Asset protection, foundation structures, and cross-border continuity — including digital assets.',
    bulletsTitle: 'What We Do',
    bullet1: 'Transfer of business interests into foundations or trust structures',
    bullet2: 'Succession rules covering digital assets and private key governance',
    bullet3: 'Multi-generational continuity and family governance planning',
    bullet4: 'Protection against forced heirship and cross-border legal conflicts',
    whoForTitle: 'Who This Is For',
    whoFor: 'Business owners, founders, and families who want to ensure their wealth — including unconventional or digital assets — transfers according to their wishes, with no ambiguity, no court battles, and no frozen accounts.',
    faq1q: 'Can a Liechtenstein foundation protect assets from forced heirship rules?',
    faq1a: 'Liechtenstein foundations can provide significant protection against forced heirship claims under foreign law, depending on the applicable jurisdiction and the structure of the foundation. This is a fact-specific analysis and we assess each client\'s situation individually before recommending a structure.',
    faq2q: 'What happens to crypto and digital assets when there is no succession plan?',
    faq2a: 'Without proper planning, digital assets can become inaccessible or lost entirely. Private keys may be unknown to heirs, wallet access may be tied to single devices, and legal frameworks for claiming digital assets vary widely. We build succession structures that specifically address key access, custodial arrangements, and wallet governance.',
    faq3q: 'When is the right time to start succession planning?',
    faq3a: 'Earlier than most people expect. Succession planning is most effective when designed alongside the asset structure itself — not as an afterthought when assets are already scattered. If you have meaningful wealth across more than one country, the time to plan is now.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'Succession planning works best when started early. If you want to understand your options, we are ready to have that conversation.',
    ctaButton: 'Get in Touch'
  },

  relocationPage: {
    title: 'Relocation Services',
    meta: 'Relocation services for entrepreneurs and investors moving to or from Liechtenstein, Austria, and Central Europe. Tax structuring, foundation review, and cross-border compliance.',
    bulletsTitle: 'What We Do',
    bullet1: 'Tax structuring and review before and after relocation',
    bullet2: 'Analysis of existing foundations, trusts, and companies under new residence rules',
    bullet3: 'Exit tax analysis and mitigation strategies',
    bullet4: 'Guidance on Liechtenstein and Austrian residence structures',
    whoForTitle: 'Who This Is For',
    whoFor: 'Entrepreneurs, investors, and internationally mobile professionals who are relocating to or from Central Europe and hold existing asset structures that need to be reviewed, adjusted, or rebuilt to fit their new situation.',
    faq1q: 'Does relocation affect my existing Liechtenstein foundation?',
    faq1a: 'It can. Changing your residence can affect how your home country — and your destination country — views and taxes distributions from a Liechtenstein foundation. We review the structural implications before the move and adjust the governance documentation where necessary.',
    faq2q: 'What are the tax implications of moving to Liechtenstein?',
    faq2a: 'Liechtenstein has a favourable and stable tax environment. Residency can be structured in ways that are tax-efficient for international clients, particularly those with existing Liechtenstein trust or foundation structures. Each situation depends on the source of income, existing structures, and applicable double-tax treaties.',
    faq3q: 'How early should I plan a relocation?',
    faq3a: 'Ideally six to twelve months before the intended move date. Structural adjustments, legal documentation, and tax analysis take time to do properly. Last-minute relocations often lead to avoidable tax events or compliance gaps that are difficult to correct retroactively.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If you are planning a move across borders and want to ensure your structures are ready, we can help you prepare.',
    ctaButton: 'Get in Touch'
  },

  philanthropyPage: {
    title: 'Philanthropic Structures',
    meta: 'Philanthropic foundations and charitable structures established in Liechtenstein. Lumen Advisory helps clients channel wealth into impact — with full legal transparency and governance.',
    bulletsTitle: 'What We Do',
    bullet1: 'Establishment of Liechtenstein charitable foundations',
    bullet2: 'Structuring for cross-border grant-making and impact investing',
    bullet3: 'Acceptance and deployment of traditional and digital asset donations',
    bullet4: 'Compliance, governance, and long-term stewardship',
    whoForTitle: 'Who This Is For',
    whoFor: 'Entrepreneurs and wealthy families who want their generosity to have structural integrity, legal standing, and long-term impact — and who want to give in an organised, transparent, and professionally governed way.',
    faq1q: 'What is a Liechtenstein charitable foundation?',
    faq1a: 'A Liechtenstein charitable foundation is a legally independent entity established to pursue specific public benefit purposes. It is governed by the Liechtenstein Persons and Companies Act (PGR) and can hold a wide range of assets. It is recognised internationally and can operate cross-border grant-making activities.',
    faq2q: 'Can a foundation accept cryptocurrency donations?',
    faq2a: 'Yes. We structure philanthropic vehicles that can accept and hold digital assets, including cryptocurrencies and tokenised instruments, alongside conventional assets. The foundation\'s statutes and governance documentation are designed to accommodate digital asset inflows and outflows in a legally compliant manner.',
    faq3q: 'How is a charitable foundation different from a private foundation?',
    faq3a: 'A charitable foundation is established for public benefit purposes and its assets are permanently dedicated to those purposes. A private foundation, by contrast, may serve private beneficiaries. The distinction affects tax treatment, governance requirements, and the permanence of the dedication of assets.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If you want to give with structure and impact, we can help you build the right vehicle.',
    ctaButton: 'Get in Touch'
  },

  accountingPage: {
    title: 'Accounting & Reporting',
    meta: 'Accounting and financial reporting for Liechtenstein foundations, trusts, and cross-border structures. Consolidated statements covering traditional and digital assets.',
    bulletsTitle: 'What We Do',
    bullet1: 'Consolidated reporting across multiple jurisdictions and asset classes',
    bullet2: 'On-chain and off-chain financial statements',
    bullet3: 'Regulatory compliance reporting for fiduciary structures',
    bullet4: 'Audit-ready bookkeeping for foundations, trusts, and holding companies',
    whoForTitle: 'Who This Is For',
    whoFor: 'Clients whose asset structures span multiple countries and include both conventional and digital assets — and who need coherent, accurate, and regulation-ready financial oversight from a single provider.',
    faq1q: 'What does accounting for a Liechtenstein foundation involve?',
    faq1a: 'Liechtenstein foundations are required to maintain proper accounting records and, depending on their size and activities, may be subject to audit requirements. We prepare annual accounts, manage bookkeeping, and ensure that the foundation\'s financial records are accurate, compliant, and suitable for trustee oversight.',
    faq2q: 'How do you handle reporting for crypto holdings and DeFi positions?',
    faq2a: 'We treat digital asset holdings as part of the consolidated financial picture. This includes recording on-chain transactions, valuing cryptocurrency positions, accounting for DeFi yields and staking rewards, and applying appropriate accounting treatment across jurisdictions. Reporting is tailored to the applicable regulatory and trustee requirements.',
    faq3q: 'Do you provide audit support?',
    faq3a: 'Yes. We prepare accounts and supporting documentation to a standard that supports third-party audit. Where audit is required — either by regulation or by client preference — we coordinate with the appointed auditor and provide full documentation of the accounting basis used.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If your structures have outgrown basic bookkeeping and you need accurate, cross-border financial reporting, we can help.',
    ctaButton: 'Get in Touch'
  },

  legalNotarialPage: {
    title: 'Legal & Notarial Services',
    meta: 'Legal advice and notarial services for foundations, trusts, and cross-border structures in Liechtenstein. Execution, supervision, and structuring by licensed attorneys and notaries.',
    bulletsTitle: 'What We Do',
    bullet1: 'Establishment of foundations, trusts, and holding companies',
    bullet2: 'Notarial execution of cross-border documents and agreements',
    bullet3: 'Legal structuring for tokenised assets and digital holdings',
    bullet4: 'Ongoing legal supervision of fiduciary structures',
    whoForTitle: 'Who This Is For',
    whoFor: 'International clients who require legally sound execution of complex structures — including those involving digital assets, multiple jurisdictions, or sensitive asset transfers that demand both legal precision and notarial authority.',
    faq1q: 'Why do I need a notary for a Liechtenstein foundation?',
    faq1a: 'Under Liechtenstein law, the establishment of certain legal entities — including foundations — requires notarial execution of the founding documents. A notary verifies the identity of the parties, certifies the legal validity of the documents, and ensures compliance with formal requirements. Dr. Tomasz Klimek is a licensed notary in Liechtenstein.',
    faq2q: 'Can you execute documents across multiple jurisdictions?',
    faq2a: 'Yes. Our team is admitted to practice in Liechtenstein, Austria, and Poland. For cross-border matters involving other jurisdictions, we coordinate with trusted local counsel. We are experienced in managing the legal formalities required when documents must be valid in more than one country.',
    faq3q: 'What is the role of a Liechtenstein attorney in a foundation structure?',
    faq3a: 'A Liechtenstein attorney ensures that the foundation\'s statutes, governance documents, and operational decisions remain legally sound and enforceable. This includes reviewing beneficiary arrangements, advising on regulatory obligations, and supervising any structural changes over time.',
    ctaTitle: 'Speak with our team',
    ctaDesc: 'If you need legally sound execution for a complex cross-border structure, our team is ready to help.',
    ctaButton: 'Get in Touch'
  }
};
